### ISSUE TITLE
skipping variable with zero or non-finite range

### ISSUE THREAD

**Issue by poidstotal** [markvanderloo/gower#13]
Hi and thanks for the great package
Everytime I run gower_topn(x,y) or gower_dist(x,y) with x having only 1 row, the following warning happen, what does that mean and how to avoid this.

Warning message:
In gower_work(x = x, y = y, pair_x = pair_x, pair_y = pair_y, n = n,  :
  skipping variable with zero or non-finite range.

**Comment by markvanderloo** [comment]
For numerical values _a_ and _b_, their contribution to the gower distance is _|a-b|/range_, where _range_ is the difference between the largest and smallest value. The message tells you that one of the variables is constant: i.e. it has a range of zero (or `Inf`, or `NaN`).

If you suspect a bug, please provide a minimal reproducible example (please do _not_ use the reprex package) so I can track it down and fix it.
