### ISSUE TITLE
does not compile from source

### ISSUE THREAD

**Issue by luisitoCH** [markvanderloo/gower#14]
> install.packages("https://cran.r-project.org/src/contrib/gower_0.2.1.tar.gz", repos = NULL, type = "source", dependencies = TRUE)
trying URL 'https://cran.r-project.org/src/contrib/gower_0.2.1.tar.gz'
Content type 'application/x-gzip' length 138432 bytes (135 KB)
==================================================
downloaded 135 KB

* installing *source* package ‘gower’ ...
** package ‘gower’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -fopenmp -fPIC  -Wall -g -O2  -c R_register_native.c -o R_register_native.o
clang: error: unsupported option '-fopenmp'
make: *** [R_register_native.o] Error 1
ERROR: compilation failed for package ‘gower’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/gower’
Warning in install.packages :
  installation of package ‘/var/folders/qx/rp222nhj3b50644syl1k7db40000gp/T//Rtmptmksas/downloaded_packages/gower_0.2.1.tar.gz’ had non-zero exit status

**Comment by luisitoCH** [comment]
Sorry, should have provided details about my environment. Here there are:

> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.1 tools_3.6.1   
> install.packages("https://cran.r-project.org/src/contrib/gower_0.2.1.tar.gz", 
+                  repos = NULL, type = "source", dependencies = TRUE)
trying URL 'https://cran.r-project.org/src/contrib/gower_0.2.1.tar.gz'
Content type 'application/x-gzip' length 138432 bytes (135 KB)
==================================================
downloaded 135 KB

* installing *source* package ‘gower’ ...
** package ‘gower’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -fopenmp -fPIC  -Wall -g -O2  -c R_register_native.c -o R_register_native.o
clang: error: unsupported option '-fopenmp'
make: *** [R_register_native.o] Error 1
ERROR: compilation failed for package ‘gower’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/gower’
Warning in install.packages :
  installation of package ‘/var/folders/qx/rp222nhj3b50644syl1k7db40000gp/T//RtmpYAd0xs/downloaded_packages/gower_0.2.1.tar.gz’ had non-zero exit status

**Comment by markvanderloo** [comment]
The standard OSX C compiler does not support parallel computing with openMP (see also Section 5 in the [vignette](https://cran.r-project.org/web/packages/gower/vignettes/intro.pdf).

You can either disable openmp by manually removing `src/Makevars`, or, install the gcc toolchain, build R against that and then compile `gower` against that. (Or, move to another OS, Apple is rather lonely in not supporting this.).

**Comment by luisitoCH** [comment]
Thanks for your answer. I installed not from source. Your package was among the dependencies of another package. All runs fine (so far).

Best.
