### ISSUE TITLE
scalability with higher thread count?

### ISSUE THREAD

**Issue by Tagar** [markvanderloo/gower#15]
Are there any known issues on Gower implementation with higher thread count? 

We were playing with some higher thread counts (tens of them) and getting some weird scalability issues. 

Not sure if it's this library's issue, or it belongs to OpenMP problem.

Thank you for any details.

**Comment by markvanderloo** [comment]
Hi Tagar,

The only thing I can tell you is that the current implementation does not scale linearly in terms of performance (like e.g. stringdist does).

But unless you're more specific about the issues you're mentioning I can't be of any help.

**Comment by Tagar** [comment]
Hi Mark ,

Thank you for your response.

Here's information we've got from one of our customers 

> problem we are dealing with is that randomly (especially when we run many jobs at once), a random job, when running our gower function, will take significantly longer (5 - 10 minutes instead of the usually 40s) to run

that's the issue when they try to go higher with number of threads.. it's also inconsistent.. doesn't always happen. I currently don't have access to that environment, but if I do will be able to provide more information.

**Comment by markvanderloo** [comment]
These things are hard to debug. If you work on a shared machine it may be that some threads of gower are for example waiting for nodes to become available. I have not experienced this myself. Gower is used quite widely since the [recepies](https://cran.r-project.org/web/packages/recipes/index.html) package of @topepo depends on it. 

@topepo: have you heard of performance issues with `gower`?

**Comment by topepo** [comment]
We have not but it's not like we are monitoring it.

**Comment by markvanderloo** [comment]
Thanks Max, if there would be many problems you'd probably have seen some issues.

**Comment by Tagar** [comment]
Thank you for the information @topepo and @markvanderloo !!
Good to know you haven't seen this behavior. 
I will update this thread when we have more details
