### ISSUE TITLE
Is it possible to run `gower_dist` when `x` and `y` have different number of rows?

### ISSUE THREAD

**Issue by anisiomqs** [markvanderloo/gower#17]
Hi. I'd like to run `gower_dist` to calculate distances where `x` is a `m by n` dataframe, and `y` is a `p by n` dataframe, expecting a matrix of `m by p` as result. Is it possible? I'm having a warning message: `longer object length is not a multiple of shorter object length`, as if the function is trying to use broadcasting, and the result is not what I was expecting. I appreciate if you could point what I am doing wrong.

```
> gower_dist(market, mycompanies)
Warning message:
longer object length is not a multiple of shorter object length
```

Thanks in advance

**Comment by anisiomqs** [comment]
I was running some other tests today and realised that `gower_topn` can compute the results I need. I'm closing this issue. If you have other advice please comment later though.

**Comment by markvanderloo** [comment]
Thanks for closing the issue and posting the answer. It may be helpful for other users.
