### ISSUE TITLE
error: "R_get_max_threads" not resolved from current namespace (gower)

### ISSUE THREAD

**Issue by mjfountain** [markvanderloo/gower#19]
Hi there

I am using the lime package and when I load it via library() I get the following error message:

Error: package or namespace load failed for ‘lime’:
 .onLoad failed in loadNamespace() for 'gower', details:
  call: .Call("R_get_max_threads")
  error: "R_get_max_threads" not resolved from current namespace (gower)

The version of R that I am using is R 4.1.3, I can't upgrade to a different one because this version comes bundled with some software my employer has paid for. The packages available in [contrib/4.0](https://cran.rstudio.com/bin/windows/contrib/4.0/) appear to be more compatible than those in [contrib/4.1](https://cran.rstudio.com/bin/windows/contrib/4.1/) so when I installed lime and gower I used the contriburl argument to direct it to 4.0. I get the same problem with 4.1. 

I'd be very grateful for any suggestions.

Many thanks for your time.

**Comment by markvanderloo** [comment]
This is the first time I hear of this. It may be a local property of how R installed by the package you mention. I have no clue what could cause this, I'm sorry.
